  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: action/checkout@4
        - name: DigitalOcean App Platform deployment
          uses: digitalocean/app_action@v1.1.5
          with:
            app_name: ${{ vars.APP_NAME }}
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
