  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
  jobs:
    build:
      environment: prod
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
           submodules: 'recursive'
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: '18'
        - name: Install Backend dependencies
          run: npm install

        - name: DigitalOcean App Platform deployment
          uses: digitalocean/app_action@v1.1.5
          with:
            app_name: ${{ vars.APP_NAME }}
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
